
export const ALL_TEXTS: string[] = [
  "Dashboard",
  "Caregivers",
  "Medication",
  "Health Tips",
  "AI Assistant",
  "Settings",
  "User Name",
  "Emergency Alert",
  "In case of an emergency, press the SOS button to immediately notify your contacts with your location.",
  "Find Caregivers",
  "Browse our network of trusted and skilled caregivers.",
  "Medication Schedule",
  "Manage and view upcoming medication reminders.",
  "Get simple, actionable health advice for daily well-being.",
  "Smart Health Assistant",
  "Ask our AI assistant for personalized health guidance.",
  "Go to",
  "Caregiver Directory",
  "Find the perfect caregiver to meet your needs. Browse profiles, skills, and ratings.",
  "View Profile",
  "Rating",
  "Contact Information",
  "Skills",
  "Medication Schedule",
  "Stay on top of your medication with customizable reminders. View your schedule by day or week.",
  "Add Medication",
  "Mark as Taken",
  "Missed dose",
  "No medications scheduled for today.",
  "Add New Medication",
  "Fill in the details for the new medication reminder.",
  "Name",
  "Dosage",
  "Time",
  "Save Reminder",
  "Health & Wellness Tips",
  "Simple and effective tips for a healthier, safer life. This section focuses on fall prevention for seniors.",
  "Make Your Home Safer",
  "Remove clutter, small furniture, pet bowls, and electrical cords from walkways.",
  "Use non-slip mats in the bathtub and on shower floors. Consider installing grab bars inside and outside the tub or shower and next to the toilet.",
  "Ensure your home has lots of light by adding more or brighter light bulbs. Turn on lights before you enter a room.",
  "Keep items you use often within easy reach to avoid using a step stool.",
  "Stay Active and Strong",
  "Engage in regular physical activity. Activities that improve balance and leg strength, such as Tai Chi, are particularly good.",
  "Talk to your doctor or a physical therapist about the best type of exercise program for you.",
  "Wear sturdy, well-fitting shoes with non-slip soles. Avoid walking in socks or slippers with smooth soles.",
  "Review Your Health",
  "Have your doctor or pharmacist review all your medicines—both prescription and over-the-counter—to identify any that may cause side effects like dizziness or drowsiness.",
  "Get your eyes checked at least once a year and update your eyeglasses as needed.",
  "Talk to your doctor about any health conditions that could increase your risk of falling, such as vision problems, heart disease, or issues with balance.",
  "Smart Health Assistant",
  "Ask any health-related question, and our AI assistant will provide helpful guidance. Please note: this is not a substitute for professional medical advice.",
  "No messages yet. Ask a question to start the conversation!",
  "e.g., \"What are some exercises to improve balance?\"",
  "Ask a health question...",
  "Sorry, I encountered an error. Please try again.",
  "Settings",
  "Manage your account settings, profile, and preferences.",
  "Profile",
  "Update your personal information.",
  "Full Name",
  "Email Address",
  "Phone Number",
  "Save Changes",
  "Language",
  "Choose your preferred language for the app.",
  "Select Language",
  "Profile Updated",
  "Your profile information has been saved successfully.",
  "CareBridge Connect",
  "Enter App",
  "Compassionate Care, Connected.",
  "CareBridge Connect is your reliable partner in coordinating and managing senior care, ensuring peace of mind for families and dignified support for loved ones.",
  "Register as Patient",
  "Join our community to find trusted caregivers and manage your health with ease.",
  "Get Started",
  "Become a Caregiver",
  "Offer your skills and compassion to those in need. Join our network of professional caregivers.",
  "Join Now",
  "Explore the App",
  "Already a member? Jump right back in to manage schedules, find resources, and connect.",
  "Enter Dashboard",
  "Back to Home",
  "Patient Registration",
  "Create your account to get started.",
  "Create Account",
  "Caregiver Registration",
  "Join our network of professional caregivers.",
  "Skills & Certifications",
  "Short Bio",
  "Briefly describe your experience and passion for caregiving.",
  "Password",
];
